Student Name: Ramiz Sheikh

Repository URL: https://github.com/ramiz0009/Multi-Environment-Application-Deployment.git

Deployment Status: Working

Access URLs:

- Development: http://localhost:3000/dev

- Production: http://localhost:3000/prod

- Frontend: http://localhost:3000

Date of Submission: 20-11-2025
