version: "3.9"

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend_dev
      - backend_prod
    networks:
      - multienv-net
    restart: unless-stopped

  backend_dev:
    build:
      context: ./backend/dev
      dockerfile: Dockerfile
    container_name: backend_dev
    env_file:
      - ./backend/dev/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - multienv-net
    restart: unless-stopped

  backend_prod:
    build:
      context: ./backend/prod
      dockerfile: Dockerfile
    container_name: backend_prod
    env_file:
      - ./backend/prod/.env
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    networks:
      - multienv-net
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    volumes:
      - mongo_data:/data/db
    networks:
      - multienv-net

networks:
  multienv-net:
    driver: bridge

volumes:
  mongo_data:
